project:
  type: website
  output-dir: docs

website:
  
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  
  title: Pollution Occitanie 
  navbar:
    left: 
      - href: index.qmd
        text: Pollution     
      - about2.qmd
      - about.qmd
      - text: "Pollutions par grandes villes"
        menu:
          - Toulouse.qmd
          - Montpellier.qmd
          - Perpignan.qmd
    tools:
      - icon: github
        menu:
          - text: Signaler une erreur 
            url:  https://github.com/RomeoBex/Projet_Groupe_Pollution_Air_Occitanie

format:
  html:
    theme: green
    css: styles.css
    toc: true