project:
  type: website
  output-dir: docs

website:
  
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  
  title: Pollution Occitanie 
  navbar:
    left: 
      - href: index.qmd
      - text: Salle des trophées 
        menu:
          - about4.qmd    
      - text: "Pollutions par grandes villes"
        menu:
          - Toulouse.qmd
          - Montpellier.qmd
          - Perpignan.qmd
          - Agde.qmd
          - Montauban.qmd
          - Nimes.qmd
          - Lourdes.qmd 
          - Rodez.qmd 
          - Albi.qmd 
          - Lattes.qmd 
          - Beziers.qmd 
      - about.qmd
      - about2.qmd
    tools:
      - icon: github
        menu:
          - text: Signaler une erreur 
            url:  https://github.com/RomeoBex/Projet_Groupe_Pollution_Air_Occitanie

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true