project:
  type: website
  output-dir: docs
website:
  title: Pollution
  navbar:
    left: 
      - href: index.qmd
        text: Acceuil
      - about.qmd

format:
  html:
    theme: green
    css: styles.css
    toc: true