project:
  type: website
  output-dir: docs
website:
  title: Pollution Occitanie 
  navbar:
    left: 
      - href: index.qmd
        text: Pollution
      - about2.qmd
      - about.qmd
format:
  html:
    theme: green
    css: styles.css
    toc: true